import fs from 'fs';
import type { WordRecord } from '../types.js';
import { resolveOutputPath } from '../config.js';

function posLabel(pos: string): string {
  const map: Record<string, string> = {
    'Noun': 'n.',
    'Verb': 'v.',
    'Adjective': 'adj.',
    'Adverb': 'adv.',
    'Suru verb': 'v. (suru)',
    'Na-adjective': 'adj. (な)',
    'I-adjective': 'adj. (い)',
  };
  for (const [key, abbr] of Object.entries(map)) {
    if (pos.toLowerCase().includes(key.toLowerCase())) return abbr;
  }
  return pos;
}

function renderWordSection(record: WordRecord, index: number): string {
  const lines: string[] = [];

  // Word header
  lines.push(`## ${index + 1}. ${record.word}【${record.reading}】`);
  lines.push('');
  lines.push(`**${posLabel(record.pos)}** ${record.definition}`);

  if (record.altDefinitions.length > 0) {
    lines.push(`*Also:* ${record.altDefinitions.slice(0, 3).join('; ')}`);
  }

  lines.push('');
  lines.push(`> **Level:** ${record.jlptLevel} · **Domain:** ${record.domain}`);
  lines.push('');

  // Example sentences
  if (record.examples.length > 0) {
    lines.push('**Example from source:**');
    lines.push('');
    for (const ex of record.examples) {
      // Replace <mark> tags with **bold** for Markdown
      const markedMd = ex.plain.replace(
        new RegExp(record.word.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g'),
        `**${record.word}**`
      );
      lines.push(`> ${markedMd}`);
      lines.push(`>`);
      lines.push(`> — [Source](${ex.sourceUrl})`);
    }
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  return lines.join('\n');
}

export function writeMarkdownOutput(
  records: WordRecord[],
  date: string,
  outputDir: string
): string {
  const header = [
    `# 言葉の世界 — ${date}`,
    '',
    `*${records.length} new word${records.length !== 1 ? 's' : ''} collected*`,
    '',
    '---',
    '',
  ].join('\n');

  const body = records.map((r, i) => renderWordSection(r, i)).join('');

  const footer = [
    `*Generated by [Kotoba no Sekai](https://github.com/kotoba-no-sekai) on ${date}*`,
  ].join('\n');

  const content = header + body + footer;

  const filename = `digest-${date}.md`;
  const outPath = resolveOutputPath(outputDir, filename);
  fs.writeFileSync(outPath, content, 'utf8');
  console.log(`[output] Markdown → ${outPath}`);
  return outPath;
}
